### PR TITLE
Build status widget

### PR DESCRIPTION
**Pull request by ArturGajowy**
in the spirit of mozaik-ext-jenkins JobStatus

Supports branch selection (default is 'master') and custom titles (default is '$owner / $repo / $branch')

Also the build title is a link for the convenience of dashboard users ('uh oh! Some build failed! Let's open the dashboard and click the link instead of searching our CI for it')

### CODE REVIEW

**Comment by ArturGajowy** [comment]
Fixed eslint errors.

**Comment by duxet** [comment]
Good job 👍

**Comment by ArturGajowy** [comment]
There's more changes in my forks, see:
https://github.com/plouc/mozaik-ext-travis/network
https://github.com/plouc/mozaik-ext-jenkins/network
https://github.com/plouc/mozaik/network

I'll be glad to open PRs for those as soon as the previous ones get merged :)

cc @plouc

**Review by plouc — CHANGES_REQUESTED** [review]
@ArturGajowy, one more time, sorry for te late review, if you're interested, this extension has already been ported to work on Mozaïk v2 https://github.com/plouc/mozaik-ext-travis/tree/mozaik-2, I think it could be nice if this widget is also available in V2.

**Pull request closed without merging**
